default: &default
  adapter: postgresql
  user: <%= ENV['HOMEY_DB_USER'] %>
  password: <%= ENV['HOMEY_DB_PASSWORD'] %>
  host: <%= ENV['HOMEY_DB_HOST'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: homey_development

test:
  <<: *default
  database: homey_test

#production
#  <<: *default
  #  database: homey_production